dist: precise

language:
  - cpp

matrix:
  include:
#    - compiler: g++
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - boost-latest
#          packages:
#            - gcc-4.9
#            - g++-4.9
#            - libboost1.55-all-dev
#            - libeigen3-dev
#      env: COMPILER=g++-4.9
    - compiler: clang
            addons:
              apt:
                sources:
                  - ubuntu-toolchain-r-test
                  - llvm-toolchain-precise-3.6
                  - boost-latest
                packages:
                  - clang-3.7
                  - libboost1.55-all-dev
                  - libeigen3-dev
            env: COMPILER=clang++-3.7


script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ..
  - make
  - ./tests

notifications:
  email: false
