language:
  - cpp

addons:
  apt:
    source:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - libboost-all-dev
      - libeigen3-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./aTest

notifications:
  email: false
