language:
  - cpp

addons:
  apt:
    source:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libboost-all-dev
      - libeigen3-dev

before_install:
  - pip install -user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./aTest

notifications:
  email: false
