dist: precise

language:
  - cpp

matrix:
  include:
    - compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
          packages:
            - gcc-5
            - g++-5
            - libboost1.55-all-dev
            - libeigen3-dev
      env: COMPILER=g++-5
      - compiler: clang
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
              - boost-latest
            packages:
              - clang-3.7
              - libboost1.55-all-dev
              - libeigen3-dev
              - llvm-toolchain-precise-3.7
        env: COMPILER=clang++-3.7


script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ..
  - make
  - ./tests

notifications:
  email: false
